"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from config.settings import *  # NOQA


WSGI_APPLICATION = 'config.debug.wsgi.application'
ASGI_APPLICATION = 'config.debug.routing.application'
