---
group: webapps
user: userapps
home: /webapps
path_venv: "/opt/venv" # Recuerda modificar travis si cambias este valor

# Estas contraseñas deben coincidir con las postgres
database_name: wagtaildb
postgresql_user: userdb
postgresql_password: password

# ADMIN User django
django_user: admin
django_email: admin@admin.com
django_password: admin
django_settings: config.settings.local

# NGINX config
server_name: localhost 127.0.0.1 0.0.0.0

# Configuraciones de zappa para producción
prod_database_name: "{{ vault_database_name }}"
prod_postgresql_user: "{{ vault_postgresql_user }}"
prod_postgresql_password: "{{ vault_postgresql_password }}"
prod_database_host: "{{ vault_postgresql_host }}"
prod_database_port: "{{ vault_postgresql_port }}"
prod_email_pass: "{{ vault_email_pass }}"

prod_redis_host: "{{vault_redis_host}}"
prod_secret_key: "{{vault_secret_key}}"
